CREATE TABLE VDMS.SALE_ORDER_PAYMENT_TRANSHIS (
  TRANSACTION_ID NUMBER(10),
  ORDER_PAYMENT_ID NUMBER(10) NOT NULL,
  ORDERID NUMBER(10),
  TRANSACTION_TYPE CHAR(2) NOT NULL,
  TRANSACTION_DATE TIMESTAMP(6) NOT NULL,
  MODIFIED_DATE TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(50) NOT NULL,
  AMOUNT NUMBER NOT NULL,
  DESCRIPTION NVARCHAR2(40),
  CONSTRAINT FK_SALE_ORDER_PAYMENT_TRANSHI1 FOREIGN KEY (ORDER_PAYMENT_ID)
    REFERENCES VDMS.SALE_ORDER_PAYMENT(ORDER_PAYMENT_ID),
  CONSTRAINT PK_PAYMENT_TRANSACTION_ID PRIMARY KEY (TRANSACTION_ID))
TABLESPACE SYSTEM
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING
NOMONITORING;
/

CREATE SEQUENCE VDMS.SEQ_PAYMENT_TRANSHIS
  START WITH 1
  INCREMENT BY 1
  CACHE 20
  NOCYCLE
  NOORDER;
/

create or replace trigger VDMS.SALE_ORDER_PAYMENT_TH_PK
before insert on VDMS.SALE_ORDER_PAYMENT_TRANSHIS
for each row
begin
if :new.TRANSACTION_ID is null 
then
select VDMS.SEQ_PAYMENT_TRANSHIS.NEXTVAL into :new.TRANSACTION_ID from dual;
end if;
end;
/