-- make transactions that indicate the receiving action of destination branch in stock adjusting.

insert all
when TRANSACTIONTYPE = 3 then
into SALE_TRANSHIS (REFERENCEORDERID, TRANSACTIONTYPE, TRANSACTIONDATE, ACTUALCOST, MODIFIEDDATE, FROMBRANCH, TOBRANCH, ITEMINSTANCEID, MODIFIEDBY, OLDENGINENO)
values (REFERENCEORDERID, 10, TRANSACTIONDATE, ACTUALCOST, (select SYSDATE from dual), FROMBRANCH, TOBRANCH, ITEMINSTANCEID, MODIFIEDBY, OLDENGINENO)
select * from SALE_TRANSHIS;

commit;