--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Thang Long Software
-- Project :      VDMS-II.DM1
-- Author :       Quang Minh
--
-- Date Created : Saturday, June 27, 2009 15:54:10
-- Target DBMS : Oracle 9i
--

DROP TABLE ASPNET_MEMBERSHIP CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_PERSONALIZATION CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_PROFILES CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_ROLES CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_SESSIONS CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_SITEMAP CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_USERS CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_USERSINROLES CASCADE CONSTRAINTS
;
DROP TABLE ASPNET_WEBEVENT_EVENTS CASCADE CONSTRAINTS
;
DROP SEQUENCE v2_seq_Role; 
-- 
-- TABLE: ASPNET_MEMBERSHIP 
--

CREATE TABLE ASPNET_MEMBERSHIP(
    USERID                        RAW(16)          NOT NULL,
    PASSWORD                      VARCHAR2(255),
    EMAIL                         VARCHAR2(255),
    PASSWORDQUESTION              VARCHAR2(255),
    PASSWORDANSWER                VARCHAR2(255),
    COMMENTS                      VARCHAR2(255),
    ISAPPROVED                    NUMBER(1, 0),
    ISLOCKEDOUT                   NUMBER(1, 0),
    CREATIONDATE                  DATE,
    LASTLOGINDATE                 DATE,
    LASTPASSWORDCHANGEDDATE       DATE,
    LASTLOCKOUTDATE               DATE,
    FAILEDPASSWORDATTEMPTCOUNT    NUMBER(9, 0),
    FAILEDPASSWORDATTEMPTSTART    DATE,
    FAILEDPASSWORDANSWERCOUNT     NUMBER(9, 0),
    FAILEDPASSWORDANSWERSTART     DATE,
    CONSTRAINT ASPNET_MEMBERSHIP_USERID_PK PRIMARY KEY (USERID)
)
;



-- 
-- TABLE: ASPNET_PERSONALIZATION 
--

CREATE TABLE ASPNET_PERSONALIZATION(
    USERID                 VARCHAR2(50)     DEFAULT NULL NOT NULL,
    PATH                   VARCHAR2(255),
    APPLICATIONNAME        VARCHAR2(255),
    PERSONALIZATIONBLOB    BLOB,
    CONSTRAINT ASPNET_PERSONAL_USERID_PK PRIMARY KEY (USERID)
)
;



-- 
-- TABLE: ASPNET_PROFILES 
--

CREATE TABLE ASPNET_PROFILES(
    USERID                  RAW(16),
    PROPERTYNAMES           BLOB       NOT NULL,
    PROPERTYVALUESSTRING    BLOB       NOT NULL,
    PROPERTYVALUESBINARY    BLOB,
    LASTUPDATEDDATE         DATE       NOT NULL
)
;



-- 
-- TABLE: ASPNET_ROLES 
--

CREATE TABLE ASPNET_ROLES(
    ROLEID             RAW(16)          NOT NULL,
    RoleIndex          NUMBER(10, 0)    NOT NULL,
    APPLICATIONNAME    VARCHAR2(255)    NOT NULL,
    ROLENAME           VARCHAR2(255)    NOT NULL,
    ParentRoleIndex    NUMBER(10, 0),
    CONSTRAINT PK23 PRIMARY KEY (RoleIndex)
)
;



-- 
-- TABLE: ASPNET_SESSIONS 
--

CREATE TABLE ASPNET_SESSIONS(
    SESSIONID          VARCHAR2(80)     NOT NULL,
    APPLICATIONNAME    VARCHAR2(255)    NOT NULL,
    CREATED            DATE             NOT NULL,
    EXPIRES            DATE             NOT NULL,
    LOCKDATE           DATE             NOT NULL,
    LOCKID             NUMBER           NOT NULL,
    TIMEOUT            NUMBER           NOT NULL,
    LOCKED             NUMBER(1, 0)     NOT NULL,
    SESSIONITEMS       LONG,
    FLAGS              NUMBER           NOT NULL,
    CONSTRAINT ASPNET_SESSIONS_SESSIONID_PK PRIMARY KEY (SESSIONID)
)
;



-- 
-- TABLE: ASPNET_SITEMAP 
--

CREATE TABLE ASPNET_SITEMAP(
    NODEID             NUMBER            NOT NULL,
    APPLICATIONNAME    VARCHAR2(255)     NOT NULL,
    URL                VARCHAR2(4000),
    NAME               VARCHAR2(255),
    DESCRIPTION        VARCHAR2(512),
    ROLES              VARCHAR2(512),
    PARENTNODEID       NUMBER,
    CONSTRAINT ASPNET_SITEMAP_NODEID_PK PRIMARY KEY (NODEID, APPLICATIONNAME)
)
;



-- 
-- TABLE: ASPNET_USERS 
--

CREATE TABLE ASPNET_USERS(
    USERID              RAW(16)          NOT NULL,
    APPLICATIONNAME     VARCHAR2(255)    NOT NULL,
    USERNAME            VARCHAR2(255),
    LASTACTIVITYDATE    DATE,
    ISANONYMOUS         NUMBER(1, 0),
    CONSTRAINT ASPNET_USERS_USERID_PK PRIMARY KEY (USERID)
)
;



-- 
-- TABLE: ASPNET_USERSINROLES 
--

CREATE TABLE ASPNET_USERSINROLES(
    USERID    RAW(16),
    ROLEID    RAW(16)
)
;



-- 
-- TABLE: ASPNET_WEBEVENT_EVENTS 
--

CREATE TABLE ASPNET_WEBEVENT_EVENTS(
    EVENTID                   CHAR(32)          NOT NULL,
    EVENTTIMEUTC              DATE              NOT NULL,
    EVENTTIME                 DATE              NOT NULL,
    EVENTTYPE                 VARCHAR2(256),
    EVENTSEQUENCE             NUMBER            NOT NULL,
    EVENTOCCURRENCE           NUMBER            NOT NULL,
    EVENTCODE                 NUMBER(11, 0)     NOT NULL,
    EVENTDETAILCODE           NUMBER(11, 0)     NOT NULL,
    MESSAGE                   VARCHAR2(1024),
    APPLICATIONPATH           VARCHAR2(256),
    APPLICATIONVIRTUALPATH    VARCHAR2(256),
    MACHINENAME               VARCHAR2(256),
    REQUESTURL                VARCHAR2(1024),
    EXCEPTIONTYPE             VARCHAR2(256),
    DETAILS                   LONG,
    CONSTRAINT SYS_C003704 PRIMARY KEY (EVENTID)
)
;



-- 
-- INDEX: ASPNET_PROFILES_USERID_KEY 
--

CREATE UNIQUE INDEX ASPNET_PROFILES_USERID_KEY ON ASPNET_PROFILES(USERID)
;
-- 
-- INDEX: ASPNET_ROLES_ROLENAME_KEY 
--

CREATE UNIQUE INDEX ASPNET_ROLES_ROLENAME_KEY ON ASPNET_ROLES(ROLENAME, APPLICATIONNAME)
;
-- 
-- INDEX: ASPNET_USERS_USERNAME_PK 
--

CREATE UNIQUE INDEX ASPNET_USERS_USERNAME_PK ON ASPNET_USERS(USERNAME, APPLICATIONNAME)
;
-- 
-- INDEX: USERIDROLEID_KEY 
--

CREATE UNIQUE INDEX USERIDROLEID_KEY ON ASPNET_USERSINROLES(USERID)
;
-- 
-- TABLE: ASPNET_MEMBERSHIP 
--

ALTER TABLE ASPNET_MEMBERSHIP ADD CONSTRAINT ASPNET_MEMBERSHIP_USERID_REF 
    FOREIGN KEY (USERID)
    REFERENCES ASPNET_USERS(USERID) ON DELETE CASCADE
;


-- 
-- TABLE: ASPNET_PROFILES 
--

ALTER TABLE ASPNET_PROFILES ADD CONSTRAINT ASPNET_PROFILES_USERID_REF 
    FOREIGN KEY (USERID)
    REFERENCES ASPNET_USERS(USERID) ON DELETE CASCADE
;


-- 
-- TABLE: ASPNET_ROLES 
--

ALTER TABLE ASPNET_ROLES ADD CONSTRAINT RefASPNET_ROLES121 
    FOREIGN KEY (ParentRoleIndex)
    REFERENCES ASPNET_ROLES(RoleIndex)
;


-- 
-- TABLE: ASPNET_SITEMAP 
--

ALTER TABLE ASPNET_SITEMAP ADD CONSTRAINT ASPNET_SITEMAP_NODEID_FK 
    FOREIGN KEY (PARENTNODEID, APPLICATIONNAME)
    REFERENCES ASPNET_SITEMAP(NODEID, APPLICATIONNAME)
;


-- 
-- TABLE: ASPNET_USERSINROLES 
--

ALTER TABLE ASPNET_USERSINROLES ADD CONSTRAINT ASPNET_USERSINROLES_USERID_REF 
    FOREIGN KEY (USERID)
    REFERENCES ASPNET_USERS(USERID) ON DELETE CASCADE
;


-- 
-- TRIGGER: ASPNET_ROLES_U_PK 
--

CREATE SEQUENCE v2_seq_Role MINVALUE 1 MAXVALUE  
999999999999999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20; 
 
CREATE OR REPLACE TRIGGER v2_p_Roles_U_PK BEFORE INSERT ON ASPNET_ROLES 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN 
SELECT v2_seq_Role.NEXTVAL INTO :NEW.RoleIndex FROM DUAL;
END; 

/

