<%@ Page Title="Dealer List" Language="C#" MasterPageFile="~/MP/MasterPage.master"
    AutoEventWireup="true" CodeFile="Dealer.aspx.cs" Inherits="Admin_Security_Dealer"
    Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="h" runat="Server">

    <script type="text/javascript">
        function updated(refresh) {
            //  close the popup
            tb_remove();
            //  refresh the update panel so we can view the changes
            if (refresh) window.location.reload(true);
        }
    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="c" runat="Server">
    <asp:ObjectDataSource ID="odsDealerList" runat="server" EnablePaging="True" TypeName="VDMS.II.BasicData.DealerDAO"
        SelectMethod="FindByCode" SelectCountMethod="CountByCode" 
        DeleteMethod="Delete" OldValuesParameterFormatString="original_{0}">
        <DeleteParameters>
            <asp:Parameter Name="DealerCode" Type="String" />
        </DeleteParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="txtDealerCode" Name="dealerCode" PropertyName="Text"
                Type="String" />
            <asp:ControlParameter ControlID="ddlautoinstockpart" 
                Name="autoinstockpart" PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="ddlautoinstockvehicle" 
                Name="autoinstockvehicle" PropertyName="SelectedValue" Type="String" />
        </SelectParameters>
    </asp:ObjectDataSource>
    <div class="form">
        <table>
            <tr>
                <td>
                    <asp:Literal ID="Literal1" runat="server" Text="Dealer code:" meta:resourcekey="Literal1Resource1"></asp:Literal>
                </td>
                <td>
                    <asp:TextBox ID="txtDealerCode" runat="server"></asp:TextBox>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Literal ID="Literal2" runat="server" Text="Auto Instock(part):" meta:resourcekey="Literal2Resource1"></asp:Literal>
                </td>
                <td>
                    <asp:DropDownList ID="ddlautoinstockpart" runat="server">
                        <asp:ListItem Value="" Text="All"></asp:ListItem>
                        <asp:ListItem Value="true" Text="ON"></asp:ListItem>
                        <asp:ListItem Value="false" Text="OFF"></asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Literal ID="Literal3" runat="server" Text="Auto Instock(vehicle):" meta:resourcekey="Literal3Resource1"></asp:Literal>
                </td>
                <td>
                    <asp:DropDownList ID="ddlautoinstockvehicle" runat="server">
                        <asp:ListItem Value="" Text="All"></asp:ListItem>
                        <asp:ListItem Value="true" Text="ON"></asp:ListItem>
                        <asp:ListItem Value="false" Text="OFF"></asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Button ID="btnFind" runat="server" Text="Search" meta:resourcekey="btnFindResource1"
                        OnClick="btnFind_Click" />
                </td>
                <td>
                </td>
            </tr>
        </table>
    </div>
    <div style="padding: 3px; width: 100%; float: left">
        <div class="grid">
            <vdms:PageGridView ID="gv" runat="server" DataSourceID="odsDealerList" AllowPaging="True"
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="DealerCode"
                OnRowDataBound="gv_RowDataBound" meta:resourcekey="gvResource1">
                <Columns>
                    <asp:BoundField DataField="DealerCode" HeaderText="Dealer Code" meta:resourcekey="BoundFieldResource1" />
                    <asp:BoundField DataField="ParentCode" HeaderText="Parent Code" meta:resourcekey="BoundFieldResource2" />
                    <asp:BoundField DataField="DealerName" HeaderText="Dealer Name" meta:resourcekey="BoundFieldResource3" />
                    <asp:TemplateField HeaderText="Auto in Stock(Part/Vehicle)" meta:resourcekey="BoundFieldResource5">
                        <ItemTemplate>
                            <%# (bool)Eval("AutoInStockPartStatus") ? "ON":"OFF" %>
                            /
                            <%# (bool)Eval("AutoInStockVehicleStatus") ? "ON" : "OFF"%>
                        </ItemTemplate>
                    </asp:TemplateField>
                   <%-- <asp:BoundField DataField="ReceiveSpan" HeaderText="Receive Span" meta:resourcekey="BoundFieldResource4" />--%>
                    <asp:HyperLinkField Text="Create account Admin" DataNavigateUrlFields="DealerCode"
                        DataNavigateUrlFormatString="CreateDealerAdmin.aspx?d={0}&TB_iframe=true&height=150&width=280"
                        ControlStyle-CssClass="thickbox" meta:resourcekey="HyperLinkFieldResource1">
                        <ControlStyle CssClass="thickbox"></ControlStyle>
                    </asp:HyperLinkField>
                </Columns>
                <EmptyDataTemplate>
                    <b>
                        <asp:Localize ID="litNotFound" runat="server" Text="There are not any dealers." meta:resourcekey="litNotFoundResource1"></asp:Localize></b>
                </EmptyDataTemplate>
            </vdms:PageGridView>
        </div>
        <asp:Button ID="b1" runat="server" Text="Add new Dealer" OnClientClick="javascript:location.href='DealerEdit.aspx'; return false;"
            meta:resourcekey="b1Resource1" />
    </div>
    <%--Create account admin--%>
    <%--<div style="padding: 3px; width: 33%; float: right;">
		<asp:PlaceHolder ID="phCreateAdmin" runat="server" Visible="false">
			<div class="normalBox">
				<table cellpadding="2" cellspacing="2" border="0" width="100%">
					<tr>
						<td style="width: 35%">
							<asp:Image ID="image2" runat="server" SkinID="RequireField" meta:resourcekey="imageResource1" />
							<asp:Localize ID="litDealerCode" runat="server" Text="Dealer Code:" meta:resourcekey="litUsernameResource1"></asp:Localize>
						</td>
						<td>
							<asp:TextBox runat="server" ID="txtDealer" ReadOnly="true"></asp:TextBox>
						</td>
					</tr>
					<tr>
						<td style="width: 25%">
							<asp:Image ID="image" runat="server" SkinID="RequireField" />
							<asp:Localize ID="litUsername" runat="server" Text="UserName:"></asp:Localize>
						</td>
						<td>
							<asp:TextBox runat="server" ID="txtUserName" Text="admin" ReadOnly="true"></asp:TextBox>
						</td>
					</tr>
					<tr>
						<td>
							<asp:Image ID="image1" runat="server" SkinID="RequireField" meta:resourcekey="imageResource1" />
							<asp:Localize ID="litPassword" runat="server" Text="Password:"></asp:Localize>
						</td>
						<td>
							<asp:TextBox runat="server" ID="txtPassword"></asp:TextBox>
						</td>
					</tr>
					<tr>
						<td>
						</td>
						<td>
							<asp:Button ID="cmdCreate" runat="server" Text="Create" OnClick="cmdCreate_Click" />
							<asp:Button ID="cmdCancel" runat="server" Text="Cancel" OnClick="cmdCancel_Click" />
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<asp:Label ID="ActionOk" runat="server" Text="Action completed. New user has been created."
								Visible="false"></asp:Label>
							<asp:Label ID="ActionFaild" runat="server" ForeColor="Red" Text="Acion faild. No user created."
								Visible="false"></asp:Label>
						</td>
					</tr>
				</table>
			</div>
		</asp:PlaceHolder>
	</div>--%>
</asp:Content>
