<%@ Page Language="C#" MasterPageFile="~/MP/Popup.master" AutoEventWireup="true"
	CodeFile="Favourite.aspx.cs" Inherits="Part_Inventory_Favourite" Theme="Thickbox"
	Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" %>

<%@ Register TagName="UpdateProgress" TagPrefix="cc1" Src="~/Controls/UpdateProgress.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="h" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="c" runat="Server">
	<div class="grid" style="width: 420px;">
		<div class="title">
			<asp:Literal ID="Literal1" runat="server" Text="My Favourite" meta:resourcekey="Literal1Resource1"></asp:Literal>
		</div>
		<asp:UpdatePanel ID="up1" runat="server" UpdateMode="Conditional">
			<ContentTemplate>
				<cc1:UpdateProgress ID="upg1" runat="server" />
				<asp:RadioButtonList ID="rblType" runat="server" AutoPostBack="True" RepeatDirection="Horizontal"
					RepeatLayout="Flow" meta:resourcekey="rblTypeResource1">
					<asp:ListItem Selected="True" Value="P" meta:resourcekey="ListItemResource1"></asp:ListItem>
					<asp:ListItem Value="A" meta:resourcekey="ListItemResource2"></asp:ListItem>
				</asp:RadioButtonList>
				|
				<asp:Localize ID="litName" runat="server" Text="Part Code:" 
					meta:resourcekey="litNameResource1"></asp:Localize>
				<asp:TextBox ID="txtPC" runat="server" meta:resourcekey="txtPCResource1"></asp:TextBox>
				<asp:Button ID="cmd1" runat="server" OnClick="cmd1_Click" Text="Filter" 
					meta:resourcekey="cmd1Resource1" />
				<vdms:PageGridView ID="gv1" runat="server" PageSize="10" DataSourceID="odsPartList"
					DataKeyNames="PartCode" AutoGenerateDeleteButton="True" meta:resourcekey="gv1Resource1">
					<Columns>
						<asp:TemplateField meta:resourcekey="TemplateFieldResource1">
							<ItemTemplate>
								<asp:CheckBox runat="server" meta:resourcekey="CheckBoxResource1" />
							</ItemTemplate>
						</asp:TemplateField>
						<asp:BoundField HeaderText="Part Code" DataField="PartCode" meta:resourcekey="BoundFieldResource1" />
						<asp:BoundField HeaderText="English Name" DataField="EnglishName" meta:resourcekey="BoundFieldResource2" />
						<asp:BoundField HeaderText="Rank" DataField="Rank" meta:resourcekey="BoundFieldResource3" />
					</Columns>
					<EmptyDataTemplate>
						<asp:Literal ID="Literal1" runat="server" Text="There is not any favorite part."
							meta:resourcekey="Literal1Resource2"></asp:Literal>
					</EmptyDataTemplate>
				</vdms:PageGridView>
			</ContentTemplate>
		</asp:UpdatePanel>
		<div class="footer">
			<asp:LinkButton ID="btnSave" runat="server" Text="Save" OnClick="BtnSave_Click" meta:resourcekey="btnSaveResource1" />
		</div>
	</div>
	<asp:ObjectDataSource ID="odsPartList" runat="server" TypeName="VDMS.II.PartManagement.PartDAO"
		SelectMethod="FindFavorite" SelectCountMethod="GetFavoriteCount" DeleteMethod="DeleteFavorite"
		EnablePaging="True">
		<SelectParameters>
			<asp:ControlParameter ControlID="rblType" Name="partType" PropertyName="SelectedValue"
				Type="String" />
			<asp:ControlParameter ControlID="txtPC" Name="partCode" PropertyName="Text" Type="String" />
			<asp:QueryStringParameter DefaultValue="O" Name="favType" QueryStringField="ftype"
				Type="String" />
		</SelectParameters>
		<DeleteParameters>
			<asp:QueryStringParameter DefaultValue="O" Name="favType" QueryStringField="ftype"
				Type="String" />
		</DeleteParameters>
	</asp:ObjectDataSource>
</asp:Content>
