--
-- ER/Studio 8.0 SQL Code Generation
-- Project :      DATA MODEL
--
-- Date Created : Tuesday, April 14, 2009 16:35:43
-- Target DBMS : Oracle 9i
--

DROP TABLE TC_VDP_FILE CASCADE CONSTRAINTS
;
DROP TABLE TC_VDQ_FILE CASCADE CONSTRAINTS
;
DROP TABLE TC_VDR_FILE CASCADE CONSTRAINTS
;
-- 
-- TABLE: TC_VDP_FILE 
--

CREATE TABLE TC_VDP_FILE(
    TC_VDP01    NUMBER(19, 0)    NOT NULL,
    TC_VDP02    VARCHAR2(30),
    TC_VDP03    VARCHAR2(30)     NOT NULL,
    TC_VDP04    VARCHAR2(30)     NOT NULL,
    TC_VDP05    VARCHAR2(30),
    TC_VDP06    TIMESTAMP(6)     NOT NULL,
    TC_VDP07    TIMESTAMP(6),
    TC_VDP08    TIMESTAMP(6),
    TC_VDP09    TIMESTAMP(6),
    TC_VDP10    TIMESTAMP(6),
    TC_VDP11    CHAR(1)          NOT NULL,
    TC_VDP12    CHAR(2),
    TC_VDP13    CHAR(1),
    TC_VDP14    VARCHAR2(250),
    TC_VDP15    CHAR(3),
    TC_VDP16    VARCHAR2(200),
    TC_VDP17    NUMBER(10, 0),
    TC_VDP18    TIMESTAMP(6),
    CONSTRAINT IPK01 PRIMARY KEY (TC_VDP01)
)
;



-- 
-- TABLE: TC_VDQ_FILE 
--

CREATE TABLE TC_VDQ_FILE(
    TC_VDQ01    NUMBER(19, 0)    NOT NULL,
    TC_VDQ02    NUMBER(38, 0)    NOT NULL,
    TC_VDQ03    VARCHAR2(30),
    TC_VDQ04    NUMBER(38, 0),
    TC_VDQ05    NUMBER(38, 0),
    TC_VDQ06    NUMBER(19, 0)    NOT NULL,
    TC_VDQ07    VARCHAR2(299),
    TC_VDQ08    NUMBER(10, 0),
    TC_VDQ09    TIMESTAMP(6),
    TC_VDQ10    CHAR(1),
    TC_VDQ11    CHAR(10),
    CONSTRAINT IPK02 PRIMARY KEY (TC_VDQ01, TC_VDQ02)
)
;



-- 
-- TABLE: TC_VDR_FILE 
--

CREATE TABLE TC_VDR_FILE(
    TC_VDR01    NUMBER(19, 0)    NOT NULL,
    TC_VDR02    NUMBER(38, 0)    NOT NULL,
    TC_VDR03    VARCHAR2(30)     NOT NULL,
    TC_VDR04    VARCHAR2(40)     NOT NULL,
    TC_VDR05    NUMBER(38, 0)    NOT NULL,
    TC_VDR06    TIMESTAMP(6)     NOT NULL,
    TC_VDR07    CHAR(1)          NOT NULL,
    CONSTRAINT IPK3 PRIMARY KEY (TC_VDR01, TC_VDR02)
)
;



-- 
-- TABLE: TC_VDQ_FILE 
--

ALTER TABLE TC_VDQ_FILE ADD CONSTRAINT RefTC_VDP_FILE1 
    FOREIGN KEY (TC_VDQ01)
    REFERENCES TC_VDP_FILE(TC_VDP01)
;


-- 
-- TABLE: TC_VDR_FILE 
--

ALTER TABLE TC_VDR_FILE ADD CONSTRAINT RefTC_VDP_FILE3 
    FOREIGN KEY (TC_VDR01)
    REFERENCES TC_VDP_FILE(TC_VDP01)
;


