//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 1/29/2009 4:08:04 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace VDMS.II.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name = "VDMS")] 
	[ProviderAttribute(typeof(Devart.Data.Oracle.Linq.Provider.OracleDataProvider))] 
	public partial class VDMSDataContext : Devart.Data.Linq.DataContext
	{
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

		#region Extensibility Method Definitions
		partial void OnCreated();
		partial void InsertFile(VDMS.II.Entity.File instance);
		partial void UpdateFile(VDMS.II.Entity.File instance);
		partial void DeleteFile(VDMS.II.Entity.File instance);
		partial void InsertMessage(VDMS.II.Entity.Message instance);
		partial void UpdateMessage(VDMS.II.Entity.Message instance);
		partial void DeleteMessage(VDMS.II.Entity.Message instance);
		#endregion

		public VDMSDataContext() :
				base(@"User Id=vdms;Password=vdms;Server=vdms;Unicode=True", mappingSource)
		{
			OnCreated();
		}

		public VDMSDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public VDMSDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public VDMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public VDMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public Devart.Data.Linq.Table<VDMS.II.Entity.File> Files
		{
			get
			{
				return this.GetTable<VDMS.II.Entity.File>();
			}
		}

		public Devart.Data.Linq.Table<VDMS.II.Entity.Message> Messages
		{
			get
			{
				return this.GetTable<VDMS.II.Entity.Message>();
			}
		}
	}
}

namespace VDMS.II.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;

	[Table(Name = @"VDMS.V2_DATA_FILE")]
	public partial class File : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Int64 _FileId;

		private System.Int64 _MessageId;

		private System.String _FileName;

		private System.Byte[] _Body;

		private EntityRef<Message> _Message;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
			partial void OnFileIdChanging(System.Int64 value);
		partial void OnFileIdChanged();
		partial void OnMessageIdChanging(System.Int64 value);
		partial void OnMessageIdChanged();
		partial void OnFileNameChanging(System.String value);
		partial void OnFileNameChanged();
		partial void OnBodyChanging(System.Byte[] value);
		partial void OnBodyChanged();
		#endregion

		public File()
		{
			this._Message = default(EntityRef<Message>);
			OnCreated();
		}

		[Column(Name = @"FILE_ID", Storage = "_FileId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "NUMBER(10) NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
		public System.Int64 FileId
		{
			get
			{
				return this._FileId;
			}
			set
			{
				if (this._FileId != value)
				{
					this.OnFileIdChanging(value);
					this.SendPropertyChanging();
					this._FileId = value;
					this.SendPropertyChanged("FileId");
					this.OnFileIdChanged();
				}
			}
		}

		[Column(Name = @"MESSAGE_ID", Storage = "_MessageId", CanBeNull = false, DbType = "NUMBER(10) NOT NULL")]
		public System.Int64 MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if (this._MessageId != value)
				{
					if (this._Message.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMessageIdChanging(value);
					this.SendPropertyChanging();
					this._MessageId = value;
					this.SendPropertyChanged("MessageId");
					this.OnMessageIdChanged();
				}
			}
		}

		[Column(Name = @"FILE_NAME", Storage = "_FileName", CanBeNull = false, DbType = "NVARCHAR2(384) NOT NULL")]
		public System.String FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if (this._FileName != value)
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}

		[Column(Name = @"BODY", Storage = "_Body", CanBeNull = false, DbType = "LONG RAW NOT NULL")]
		public System.Byte[] Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if (this._Body != value)
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}

		[Association(Name="Message_File", Storage="_Message", ThisKey="MessageId", IsForeignKey=true)]
		public Message Message
		{
			get
			{
				return this._Message.Entity;
			}
			set
			{
				Message previousValue = this._Message.Entity;
				if (((previousValue != value) 
							|| (this._Message.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Message.Entity = null;
						previousValue.Files.Remove(this);
					}
					this._Message.Entity = value;
					if ((value != null))
					{
						value.Files.Add(this);
						this._MessageId = value.MessageId;
					}
					else
					{
						this._MessageId = default(System.Int64); 
					}
					this.SendPropertyChanged("Message");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if (this.PropertyChanging != null)
				this.PropertyChanging(this, emptyChangingEventArgs);
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if (this.PropertyChanged != null)
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}

	[Table(Name = @"VDMS.V2_DATA_MESSAGE")]
	public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Int64 _MessageId;

		private System.Nullable<long> _ParentId;

		private System.String _FromDealer;

		private System.String _ToDealer;

		private System.String _Body;

		private System.DateTime _CreatedDate;

		private System.String _CreatedBy;

		private System.String _Flag;

		private EntitySet<File> _Files;

		private EntitySet<Message> _Messages;

		private EntityRef<Message> _Message1;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
			partial void OnMessageIdChanging(System.Int64 value);
		partial void OnMessageIdChanged();
		partial void OnParentIdChanging(System.Nullable<long> value);
		partial void OnParentIdChanged();
		partial void OnFromDealerChanging(System.String value);
		partial void OnFromDealerChanged();
		partial void OnToDealerChanging(System.String value);
		partial void OnToDealerChanged();
		partial void OnBodyChanging(System.String value);
		partial void OnBodyChanged();
		partial void OnCreatedDateChanging(System.DateTime value);
		partial void OnCreatedDateChanged();
		partial void OnCreatedByChanging(System.String value);
		partial void OnCreatedByChanged();
		partial void OnFlagChanging(System.String value);
		partial void OnFlagChanged();
		#endregion

		public Message()
		{
			this._Files = new EntitySet<File>(new Action<File>(this.attach_Files), new Action<File>(this.detach_Files));
			this._Messages = new EntitySet<Message>(new Action<Message>(this.attach_Messages), new Action<Message>(this.detach_Messages));
			this._Message1 = default(EntityRef<Message>);
			OnCreated();
		}

		[Column(Name = @"MESSAGE_ID", Storage = "_MessageId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "NUMBER(10) NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
		public System.Int64 MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if (this._MessageId != value)
				{
					this.OnMessageIdChanging(value);
					this.SendPropertyChanging();
					this._MessageId = value;
					this.SendPropertyChanged("MessageId");
					this.OnMessageIdChanged();
				}
			}
		}

		[Column(Name = @"PARENT_ID", Storage = "_ParentId", DbType = "NUMBER(10)")]
		public System.Nullable<long> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if (this._ParentId != value)
				{
					if (this._Message1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}

		[Column(Name = @"FROM_DEALER", Storage = "_FromDealer", DbType = "VARCHAR2(30)")]
		public System.String FromDealer
		{
			get
			{
				return this._FromDealer;
			}
			set
			{
				if (this._FromDealer != value)
				{
					this.OnFromDealerChanging(value);
					this.SendPropertyChanging();
					this._FromDealer = value;
					this.SendPropertyChanged("FromDealer");
					this.OnFromDealerChanged();
				}
			}
		}

		[Column(Name = @"TO_DEALER", Storage = "_ToDealer", DbType = "VARCHAR2(30)")]
		public System.String ToDealer
		{
			get
			{
				return this._ToDealer;
			}
			set
			{
				if (this._ToDealer != value)
				{
					this.OnToDealerChanging(value);
					this.SendPropertyChanging();
					this._ToDealer = value;
					this.SendPropertyChanged("ToDealer");
					this.OnToDealerChanged();
				}
			}
		}

		[Column(Name = @"BODY", Storage = "_Body", CanBeNull = false, DbType = "NVARCHAR2(1536) NOT NULL")]
		public System.String Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if (this._Body != value)
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}

		[Column(Name = @"CREATED_DATE", Storage = "_CreatedDate", CanBeNull = false, DbType = "TIMESTAMP(6) NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if (this._CreatedDate != value)
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}

		[Column(Name = @"CREATED_BY", Storage = "_CreatedBy", CanBeNull = false, DbType = "NVARCHAR2(768) NOT NULL")]
		public System.String CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if (this._CreatedBy != value)
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}

		[Column(Name = @"FLAG", Storage = "_Flag", CanBeNull = false, DbType = "CHAR(1) NOT NULL")]
		public System.String Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if (this._Flag != value)
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}

		[Association(Name="Message_File", Storage="_Files", OtherKey="MessageId")]
		public EntitySet<File> Files
		{
			get
			{

				return this._Files;
			}
			set
			{
				this._Files.Assign(value);
			}
		}

		[Association(Name="Message_Message", Storage="_Messages", OtherKey="ParentId")]
		public EntitySet<Message> Messages
		{
			get
			{

				return this._Messages;
			}
			set
			{
				this._Messages.Assign(value);
			}
		}

		[Association(Name="Message_Message", Storage="_Message1", ThisKey="ParentId", IsForeignKey=true)]
		public Message Message1
		{
			get
			{
				return this._Message1.Entity;
			}
			set
			{
				Message previousValue = this._Message1.Entity;
				if (((previousValue != value) 
							|| (this._Message1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Message1.Entity = null;
						previousValue.Messages.Remove(this);
					}
					this._Message1.Entity = value;
					if ((value != null))
					{
						value.Messages.Add(this);
						this._ParentId = value.MessageId;
					}
					else
					{
						this._ParentId = default(System.Nullable<long>); 
					}
					this.SendPropertyChanged("Message1");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if (this.PropertyChanging != null)
				this.PropertyChanging(this, emptyChangingEventArgs);
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if (this.PropertyChanged != null)
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}

		private void attach_Files(File entity)
		{
			this.SendPropertyChanging();
			entity.Message = this;
		}
		
		private void detach_Files(File entity)
		{
			this.SendPropertyChanging();
			entity.Message = null;
		}

		private void attach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Message1 = this;
		}
		
		private void detach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Message1 = null;
		}
	}
}
